spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/omnibus}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.flywaydb: info