CREATE TABLE users
(
    id            UUID                  DEFAULT gen_random_uuid(),
    name          VARCHAR(150) NOT NULL,
    email         VARCHAR(200) NOT NULL,
    password_hash VARCHAR(72)  NOT NULL,
    account_type  VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING_ACTIVATION',

    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMPTZ,

    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UNIQUE_USER_EMAIL UNIQUE (email),
    CONSTRAINT CHECK_ACCOUNT_TYPE CHECK (account_type IN ('CUSTOMER', 'STAFF')),
    CONSTRAINT CHECK_USER_STATUS
        CHECK (
            status IN ('ACTIVE', 'PENDING_ACTIVATION', 'PENDING_DELETION', 'SUSPENDED', 'BANNED')
            ),
    CONSTRAINT CHECK_USER_DELETION_CONSISTENCY CHECK (
        (status = 'PENDING_DELETION' AND deleted_at IS NOT NULL)
            OR (status <> 'PENDING_DELETION' AND deleted_at IS NULL)
        )
);

CREATE TABLE customer_profiles
(
    id         UUID NOT NULL,
    birth_date DATE NOT NULL,
    photo_url  VARCHAR(500),

    CONSTRAINT PK_CUSTOMER_PROFILES PRIMARY KEY (id),
    CONSTRAINT FK_CUSTOMER_PROFILES_USER FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE staff_profiles
(
    id            UUID        NOT NULL,
    role          VARCHAR(20) NOT NULL,
    employee_code VARCHAR(30) NOT NULL,
    department    VARCHAR(20),
    hired_at      DATE        NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT PK_STAFF_PROFILES PRIMARY KEY (id),
    CONSTRAINT FK_STAFF_PROFILES_USER FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_STAFF_EMPLOYEE_CODE UNIQUE (employee_code),
    CONSTRAINT CHECK_STAFF_ROLE CHECK (role IN ('VIEWER', 'MANAGER', 'EDITOR', 'ADMIN')),
    CONSTRAINT CHECK_STAFF_DEPARTMENT CHECK (
        department IS NULL OR department IN ('CATALOG', 'SALES', 'SUPPORT', 'IT', 'MARKETING')
        )
);

CREATE TABLE user_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      UUID        NOT NULL,
    token_hash   VARCHAR(64) NOT NULL,
    token_type   VARCHAR(20) NOT NULL,
    token_status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    target_email VARCHAR(200),
    attempts     INT         NOT NULL DEFAULT 0,
    expires_at   TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at      TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,

    CONSTRAINT PK_USER_TOKENS PRIMARY KEY (id),
    CONSTRAINT FK_USER_TOKENS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT CHECK_USER_TOKEN_TYPE CHECK (token_type IN ('ACCOUNT_ACTIVATION', 'PASSWORD_RESET',
                                                           'EMAIL_CHANGE')),
    CONSTRAINT CHECK_USER_TOKEN_STATUS CHECK (token_status IN ('ACTIVE', 'USED',
                                                               'REVOKED', 'EXPIRED')),
    CONSTRAINT CHECK_USER_TOKEN_EXPIRY CHECK (expires_at > created_at)
);

CREATE TABLE products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title          VARCHAR(200)   NOT NULL,
    stock_quantity INT            NOT NULL DEFAULT 0,
    status         VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',
    description    TEXT           NOT NULL,
    price          DECIMAL(10, 2) NOT NULL,
    product_type   VARCHAR(20)    NOT NULL,
    age_rating     INT            NOT NULL,
    slug           VARCHAR(200)   NOT NULL,
    sku            VARCHAR(64)    NOT NULL,

    created_at     TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_PRODUCTS PRIMARY KEY (id),
    CONSTRAINT CHECK_PRODUCT_TYPE CHECK (product_type IN ('BOOK')),
    CONSTRAINT CHECK_PRODUCT_PRICE CHECK (price >= 0),
    CONSTRAINT CHECK_PRODUCT_STOCK_QUANTITY CHECK (stock_quantity >= 0),
    CONSTRAINT CHECK_PRODUCT_AGE_RATING CHECK (age_rating IN (0, 10, 12, 14, 16, 18)),
    CONSTRAINT UNIQUE_PRODUCT_SLUG UNIQUE (slug),
    CONSTRAINT UNIQUE_PRODUCT_SKU UNIQUE (sku),
    CONSTRAINT CHECK_PRODUCT_STATUS CHECK ( status in ('ACTIVE', 'OUT_OF_STOCK', 'COMING_SOON',
                                                       'DISCONTINUED', 'HIDDEN') )
);

CREATE TABLE product_images
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT       NOT NULL,
    image_url  VARCHAR(500) NOT NULL,
    is_primary BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order INT          NOT NULL DEFAULT 0,

    CONSTRAINT PK_PRODUCT_IMAGES PRIMARY KEY (id),
    CONSTRAINT FK_PRODUCT_IMAGES_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE books
(
    id        BIGINT       NOT NULL,
    isbn      VARCHAR(20)  NOT NULL,
    publisher VARCHAR(150) NOT NULL,

    CONSTRAINT PK_BOOKS PRIMARY KEY (id),
    CONSTRAINT FK_BOOKS_PRODUCT FOREIGN KEY (id) REFERENCES products (id),
    CONSTRAINT UNIQUE_BOOKS_ISBN UNIQUE (isbn)
);

CREATE TABLE authors
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(150) NOT NULL,
    bio         TEXT,
    nationality CHAR(2),
    photo_url   VARCHAR(500),

    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_AUTHORS PRIMARY KEY (id)
);

CREATE TABLE book_authors
(
    book_id   BIGINT      NOT NULL,
    author_id BIGINT      NOT NULL,
    role      VARCHAR(20) NOT NULL,

    CONSTRAINT PK_BOOK_AUTHORS PRIMARY KEY (book_id, author_id, role),
    CONSTRAINT FK_BOOK_AUTHORS_BOOK FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT FK_BOOK_AUTHORS_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id),
    CONSTRAINT CHECK_BOOK_AUTHOR_ROLE CHECK (role IN ('WRITER', 'ILLUSTRATOR', 'COLORIST', 'LETTERER'))
);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),

    CONSTRAINT PK_CATEGORIES PRIMARY KEY (id),
    CONSTRAINT UNIQUE_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE product_categories
(
    product_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT PK_PRODUCT_CATEGORIES PRIMARY KEY (product_id, category_id),
    CONSTRAINT FK_PRODUCT_CATEGORIES_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT FK_PRODUCT_CATEGORIES_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE languages
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code CHAR(2)     NOT NULL,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT PK_LANGUAGES PRIMARY KEY (id),
    CONSTRAINT UNIQUE_LANGUAGE_CODE UNIQUE (code)
);

CREATE TABLE product_languages
(
    product_id    BIGINT      NOT NULL,
    language_id   BIGINT      NOT NULL,
    language_type VARCHAR(20) NOT NULL,

    CONSTRAINT PK_PRODUCT_LANGUAGES PRIMARY KEY (product_id, language_id, language_type),
    CONSTRAINT FK_PRODUCT_LANGUAGES_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT FK_PRODUCT_LANGUAGES_LANGUAGE FOREIGN KEY (language_id) REFERENCES languages (id),
    CONSTRAINT CHECK_PRODUCT_LANGUAGE_TYPE CHECK (language_type IN ('TEXT', 'AUDIO'))
);

CREATE INDEX IDX_PRODUCTS_STATUS
    ON products (status);
CREATE INDEX IDX_USERS_STATUS
    ON users (status);
CREATE INDEX IDX_USER_TOKENS_USER_TYPE ON user_tokens (user_id, token_type);
CREATE INDEX IDX_PRODUCT_IMAGES_PRODUCT ON product_images (product_id);
CREATE INDEX IDX_PRODUCT_LANGUAGES_LANGUAGE ON product_languages (language_id);
CREATE INDEX IDX_PRODUCT_CATEGORIES_CATEGORY ON product_categories (category_id);
CREATE INDEX IDX_BOOK_AUTHORS_AUTHOR ON book_authors (author_id);
CREATE INDEX IDX_PRODUCTS_SEARCH
    ON products
        USING GIN (
                   to_tsvector(
                           'portuguese',
                           coalesce(title, '') || ' ' || coalesce(description, '')
                   )
            );
CREATE UNIQUE INDEX UQ_PRODUCT_PRIMARY_IMAGE
    ON product_images (product_id)
    WHERE is_primary = TRUE;
CREATE UNIQUE INDEX ux_user_token_one_active
    ON user_tokens (user_id)
    WHERE token_status = 'ACTIVE';
